branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: build
          scope: deps
          release: patch
        - type: build
          scope: deps-dev
          release: patch
        - type: refactor
          release: patch
        - type: style
          release: patch
        - type: ci
          release: patch
        - type: chore
          release: patch
        - type: docs
          release: patch
        - breaking: true
          release: major
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: docs
            section: Documentation
          - type: style
            section: Styles
          - type: refactor
            section: Refactors
          - type: perf
            section: Performance Improvements
          - type: test
            section: Tests
          - type: build
            section: Build System
          - type: ci
            section: Continuous Integration
          - type: chore
            section: Chores
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# erlang-event-sourcing-xp changelog"
  - - "semantic-release-replace-plugin"
    - replacements:
        - files: [rebar.config]
          from: "{release, {es_xp, \".*\"}"
          to: "{release, {es_xp, \"${nextRelease.version}\"}"
          countMatches: true
          results:
            - file: rebar.config
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/exec"
    - prepareCmd: ".github/scripts/generate_release_bom.escript ${nextRelease.version}"
  - - "@semantic-release/exec"
    - prepareCmd: |
        rebar3 as prod tar
  - - "@semantic-release/github"
    - successComment: false
      assets:
        - "_build/prod/rel/es_xp/es_xp-*.tar.gz"
  - - "@semantic-release/git"
    - assets:
        - README.md
        - CHANGELOG.md
        - rebar.config
        - rebar.lock
        - bom.yml
      message: "chore(release): perform release ${nextRelease.version}"
