name: Build / Erlang

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-erlang.yml'
      - 'apps/**'
      - 'rebar.config'
      - 'rebar.lock'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/build-erlang.yml'
      - 'apps/**'
      - 'rebar.config'
      - 'rebar.lock'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-erlang:
    runs-on: ubuntu-22.04
    env:
      ERL_FLAGS: "-enable-feature all"
      OTP_VERSION: "27"
      REBAR3_VERSION: "3.24.0"
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Erlang/OTP and rebar3
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR3_VERSION }}

      - name: Restore _build folder
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: _build
          key: "_build-cache-for\
            -otp-${{ env.OTP_VERSION }}\
            -rebar3-${{ env.REBAR3_VERSION }}\
            -hash-${{ hashFiles('rebar.lock') }}"

      - name: Restore rebar3's cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
            -otp-${{ env.OTP_VERSION }}\
            -rebar3-${{ env.REBAR3_VERSION }}\
            -hash-${{ hashFiles('rebar.lock') }}"

      - name: Build Erlang code
        run: rebar3 compile
