name: Release

on:
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  perform-release:
    needs:
      - lint
      - build
      - test
    runs-on: ubuntu-22.04
    env:
      ERL_FLAGS: "-enable-feature all"
      OTP_VERSION: "27"
      REBAR3_VERSION: "3.24.0"
    steps:
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Check out repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Setup Erlang/OTP and rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR3_VERSION }}

      - name: Restore _build folder
        uses: actions/cache@v4
        with:
          path: _build
          key: "_build-cache-for\
            -otp-${{ env.OTP_VERSION }}\
            -rebar3-${{ env.REBAR3_VERSION }}\
            -hash-${{ hashFiles('rebar.lock') }}"

      - name: Restore rebar3's cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
            -otp-${{ env.OTP_VERSION }}\
            -rebar3-${{ env.REBAR3_VERSION }}\
            -hash-${{ hashFiles('rebar.lock') }}"

      - name: Release project
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22.0.5
          branch: main
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
            semantic-release-replace-plugin@1.2.7
          extends: |
            conventional-changelog-conventionalcommits@7.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
